### PR TITLE
Updated to v1.0

### PR DESCRIPTION
**Pull request by pariterre**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
@romainmartinez 
```bash
import: 'pyomeca'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyomeca_1591452746372/test_tmp/run_test.py", line 2, in <module>
    import pyomeca
  File "/home/conda/feedstock_root/build_artifacts/pyomeca_1591452746372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/pyomeca/__init__.py", line 1, in <module>
    from .analogs import Analogs
  File "/home/conda/feedstock_root/build_artifacts/pyomeca_1591452746372/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/pyomeca/analogs.py", line 8, in <module>
    from pyomeca.io import read, utils
ModuleNotFoundError: No module named 'pyomeca.io'
```
Any idea?

**Comment by romainmartinez** [comment]
> Any idea?

Weird... Maybe we need an `__init__.py` in each subdirectories?

**Review by romainmartinez — APPROVED** [review]

**Comment by romainmartinez** [comment]
The latest version of `pyomeca` listed is still `2019.8.1` and not `1.0.1` (see [here](https://github.com/conda-forge/pyomeca-feedstock) or [here](https://anaconda.org/conda-forge/pyomeca)).
Is this because we changed our release mode (`year`.`major`.`minor` to `major`.`minor`.`fix`)?

**Comment by romainmartinez** [comment]
@conda-forge-admin, please ping team

**Pull request merged**
